#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
    configure)
      echo "Downloading NodeJS Dependencies"
      cd /usr/local/alivecontrol
      npm install
      exit 0
      ;;

    upgrade)
        # Upgrade package
        exit 0
        ;;

    *)
        exit 0
        ;;
esac

exit 0